### ISSUE TITLE
42Typos Typos

### ISSUE THREAD

**Issue by Ducorits** [codam-coding-college/42Typos#35]
**Project Name**
Not applicable.

**What is the issue**

In the FAQ section under "I found a typo!".
I think "stumble upon an issue", instead "stumble on an issue", is a nicer way of wording that sentence.

In the FAQ section under "I have a question rather than an issue?".
"A: Then ask you peers instead, this just for actual issues that can be seen on either the PDFs or Evaluation sheets."

"you" and "just", should probably be "your" and "is".

**Expectation**
"A: Then ask your peers instead, this is for actual issues, that can be seen on either the PDFs or Evaluation sheets."

**Additional context**

You could probably, also add a few commas in the description of the repo, to make it more readable.

**Comment by W2Wizard** [comment]
Very funny duco
