### ISSUE TITLE
Typo in Libft subject 

### ISSUE THREAD

**Issue by Jeroenvh99** [codam-coding-college/42Typos#49]
**Project Name**
[Libft](https://projects.intra.42.fr/projects/42cursus-libft)

**What is the issue**
On page 6 on the top of the page it says behaviors/

**Expectation**
I think this should be behaviours, I prefer British English.

**Comment by W2Wizard** [comment]
For future note, you can also just bundle all your issues in one go 👍

**Comment by Jeroenvh99** [comment]
I'll try that next time

**Comment by W2Wizard** [comment]
Both are valid
