### ISSUE TITLE
Typos in Libft subject

### ISSUE THREAD

**Issue by Jeroenvh99** [codam-coding-college/42Typos#50]
**Project Name**
[Libft](https://projects.intra.42.fr/projects/42cursus-libft)

**What is the issue**
- [x] On page 5 under the fifth bullet point it says "every .c files", this should be "every .c file".

- [x] ~~On page 6 in the informational section it says "It is therefore forbidden to include it in your own prototypes ...", this should be "It is therefore forbidden to include in your own prototypes ...".~~

- [x] ~~On page 7 under the ft_strjoin description it says "Allocates (with malloc(3)) and returns a new string, which is the result of the concatenation of ’s1’ and ’s2’.", this should be "Allocates (with malloc(3)) and returns a new string which is the result of the concatenation of ’s1’ and ’s2’."~~

- [x] On top of page 11 it says "Functions to manipulate memory and strings is very useful.", this should be "Functions to manipulate memory and strings are very useful."

- [x] ~~At the bottom of page 11 it says the following about linked lists: "next: The address of the next node, or NULL if the next node is the last one.", if I understand the concept of a linked list correctly this should be "next: The address of the next node, or NULL if this node is the last one."~~

- [x] On page 12 in the description of `ft_lstadd_front` it says "The address of a pointer to the node to be added to the list.", but the corresponding argument is *new, so this should say "A pointer to the node to be added to the list."

- [x] On page 13 in the description of ft_lstadd_back the same problem happens as with ft_lstadd_front.

- [x] On page 13 in the description of ft_lstdelone it says this: "Takes as a parameter a node and frees the memory of the node’s content using the function ’del’ given
as a parameter and free the node. The memory of 'next’ must not be freed.", I find this a bit confusing, I would suggest rewriting it as "Takes a node as parameter and frees the memory of
the node’s content using the function ’del’ given
as a parameter and free's the node. The memory of
’next’ must not be freed."

- [x] ~~On page 13 in the description of ft_lstclear it says about the first argument "The address of a pointer to a node.", shouldn't this be "The address of a pointer to the first node."?~~

- [x] On page 14 in the description of ft_lstiter it says "The address of the function used to iterate on
the list.", this should be "The address of the function used to iterate over the list."

- [x] On page 14 in the description of ft_lstiter it says "Iterates the list ’lst’ and applies the function
’f’ on the content of each node.", this should be "Iterates the list ’lst’ and applies the function
’f’ to the content of each node."

- [x] On page 14 in the description of ft_lstmap there are the same typos as in ft_lstiter.

**Expectation**
See the section above 

**Additional context**
I have nothing more to say

**Comment by W2Wizard** [comment]
Some of these suggestion I didn't include, the rest were not there anymore.

Everything else was fixed 👍

**Comment by Jeroenvh99** [comment]
Thanks for your time
