### ISSUE TITLE
Typos in guidelines on eval sheet 

### ISSUE THREAD

**Issue by Jeroenvh99** [codam-coding-college/42Typos#51]
**Project Name**
This issue is a collection of typos in the guidelines section on libft's eval sheet, but I think the guidelines are pretty similar for every eval sheet in the core

**What is the issue**

- Under guidelines: "... work that was turned in the Git ..." -> "that was turned in in the Git".

- Under guidelines, third point: "... no malicious aliases was used ..." -> "... no malicious aliases were used ..."

- Under guidlines, fourth point: move the word togehter to the end -> "... the grading (scripts for testing or automation) together."

- Under guidelines, ninth point: Also move together at the end of the sentence -> "... are strongly encouraged to review the work that was turned in together."

**Expectation**
See the section above 

**Additional context**
None

**Comment by W2Wizard** [comment]
Please keep it short next time, its hard to read a giant block of text and trying to figure out differences. If I have enough text I can find the rest.

**Comment by Jeroenvh99** [comment]
Ah, I see that you added bullet points, this indeed makes it easier to read

**Comment by W2Wizard** [comment]
Fixes were implemented
