### ISSUE TITLE
Typo in eval sheet 

### ISSUE THREAD

**Issue by Jeroenvh99** [codam-coding-college/42Typos#53]
** NOTE: PLEASE ACTUALLY FILL THIS IN AND DON'T JUST DISCARD IT**

**Project Name**
I noticed it in the get_next_line eval sheet, but I think this applies to the eval sheets of all projects in the core

**What is the issue**
In the introductory text for the bonus part it says "Evaluate the bonus part if, and only if, the mandatory part has been entirely and perfectly done, and the error
management handles unexpected or bad usage. In case all the mandatory points were not passed during the
defense, bonus points must be totally ignored." These two sentences are kind of contradictory, at least that's what I make of it.

**Expectation**
I would suggest reformulating those lines as "Evaluate the bonus part if, and only if, the mandatory part has been entirely and perfectly done, and the error
management handles unexpected or bad usage. In case not all of the mandatory points were passed during the
defense, bonus points must be totally ignored."

**Additional context**

**Comment by W2Wizard** [comment]
This is really not a typo nor bad grammar. All thats different in your example is the placement of `not`. I think either is simple to understand and clear enough.

**Comment by Jeroenvh99** [comment]
It's ok then
